server:
  port: 5000
spring:
  application:
    name: cym-crowd-short-message
  cloud:
    nacos:
      discovery:
        group: CROWD_GROUP
        server-addr: localhost:8848
        namespace: 293bbd0a-0222-4245-bb2d-3e066ccb5a36

short:
  message:
    host: "https://dfsns.market.alicloudapi.com"
    path: "/data/send_sms"
    header: "application/x-www-form-urlencoded; charset=UTF-8"
    method: "POST"
    appcode: "d90b68d30d8046cf97479c12b212bfaa"
    templateId: "TPL_0000"

