server:
  port: 1000
spring:
  application:
    name: cym-crowd-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: CROWD_GROUP
        namespace: 293bbd0a-0222-4245-bb2d-3e066ccb5a36
