server:
  port: 2000
spring:
  application:
    name: cym-crowd-mysql
  cloud:
    nacos:
      discovery:
        group: CROWD_GROUP
        server-addr: localhost:8848
        namespace: 293bbd0a-0222-4245-bb2d-3e066ccb5a36
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_crowd?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

# 配置mybatis-plus
mybatis-plus:
  configuration:
    #输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #*Mapper.xml文件存放位置
  mapper-locations: classpath:mapper/*Mapper.xml
