spring:
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
      chain:ject_c
      compressed: true
      enabled: true
  # 解决springboot 2.6版本循环依赖的问题，暂时恢复2.5的行为
  main:
    allow-circular-references: true
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prorowd?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  #配置thymeleaf引擎
  thymeleaf:
    #开发环境关闭缓存，生产环境开启缓存
    cache: false
  #将post请求转换为put或delete请求,restful风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true
# 解决中文乱码
server:
  port: 8888
# 配置mybatis-plus
mybatis-plus:
  configuration:
    #输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
