server:
  port: 80
spring:
  application:
    name: cym-crowd-gateway
  cloud:
    nacos:
      discovery:
        group: CROWD_GROUP
        server-addr: localhost:8848
        namespace: 293bbd0a-0222-4245-bb2d-3e066ccb5a36
    gateway:
      enabled: true
      shouldSkipUrls:
        - /
        - /auth/member/to/reg/page.html
      discovery:
        locator:
          #设置为true， 可以通过微服务创建路由功能
          enabled: true
      routes:
        - id: crowd_portal
          uri: lb://cym-crowd-auth
          predicates:
            - Path=/**






